services:
  crude:
    container_name: crude
    depends_on:
      - mongodb
    build:
      context: ./crude
    image: memmaker/crude:latest
    restart: unless-stopped
    ports:
      - 2000:2000
    environment:
      ADMIN_WALLET: 0x993a8C4EC5dF95C45A5929660062445391204fC7,0xFa7703137b9bbD0ffa942c942B60FD7670352e0C
      MONGODB_URI: mongodb://crude:by_example@mongo:27017/
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: crude
      MONGO_INITDB_ROOT_PASSWORD: by_example
    volumes:
      - ${HOME}/db_data:/data/db

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: crude
#      ME_CONFIG_MONGODB_ADMINPASSWORD: by_example
#      ME_CONFIG_MONGODB_URL: mongodb://crude:by_example@mongo:27017/

networks:
  default:
    name: dockernet
    external: true
